"use client";
import {useEffect,useState,type FormEvent} from "react";
import Link from "next/link";
type Metrics={live:{policyRecords:number;claimRecords:number;paidPremiumRecorded:number;paidClaimsRecorded:number;lossRatio:number|null};sandbox:{policyRecords:number;claimRecords:number;receiptRecords:number;receiptsSimulated:number};asOf:string};
type RequestRow={id:string;subject:string;description:string;status:string;priority:string;worker_name:string;admin_notes:string|null};
export default function Admin(){
 const [authenticated,setAuthenticated]=useState(false),[checked,setChecked]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[records,setRecords]=useState<Metrics|null>(null),[support,setSupport]=useState<RequestRow[]>([]),[busy,setBusy]=useState(false);
 async function load(){const [a,b]=await Promise.all([fetch("/api/dashboard",{cache:"no-store"}),fetch("/api/admin/service-requests",{cache:"no-store"})]);if(!a.ok||!b.ok)throw Error("Could not load administrator records");setRecords(await a.json());setSupport((await b.json()).requests||[]);}
 useEffect(()=>{fetch("/api/admin/session",{cache:"no-store"}).then(r=>r.json()).then(b=>{setAuthenticated(Boolean(b.authenticated));setChecked(true);}).catch(()=>{setChecked(true);setError("Session check failed");});},[]);
 useEffect(()=>{if(!authenticated)return;Promise.all([fetch("/api/dashboard",{cache:"no-store"}),fetch("/api/admin/service-requests",{cache:"no-store"})]).then(async([a,b])=>{if(!a.ok||!b.ok)throw Error("Could not load administrator records");setRecords(await a.json());setSupport((await b.json()).requests||[]);}).catch(e=>setError(e.message));},[authenticated]);
 async function login(e:FormEvent){e.preventDefault();setError("");setBusy(true);try{const r=await fetch("/api/admin/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})}),b=await r.json();if(!r.ok)throw Error(b.error||"Sign-in failed");setPassword("");setAuthenticated(true);}catch(e){setError(e instanceof Error?e.message:"Sign-in failed");}finally{setBusy(false);}}
 async function updateRequest(id:string,status:string){setBusy(true);setError("");try{const r=await fetch("/api/admin/service-requests",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({requestId:id,status})}),b=await r.json();if(!r.ok)throw Error(b.error||"Update failed");await load();}catch(e){setError(e instanceof Error?e.message:"Update failed");}finally{setBusy(false);}}
 return <div className="space-y-4 p-3 pb-24"><h1 className="text-2xl font-bold">Administrator records</h1><p className="text-sm">Persisted records only. No trained model, forecast or bank reconciliation. Financial approval remains disabled.</p>{error&&<p role="alert">{error}</p>}{!checked?<p>Checking session...</p>:!authenticated?<form className="space-y-3" onSubmit={login}><label className="block">Email<input className="block border p-2 w-full" type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label className="block">Password<input className="block border p-2 w-full" type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label><button disabled={busy} className="border rounded p-2">{busy?"Signing in...":"Sign in"}</button></form>:<><button className="underline" onClick={async()=>{try{const r=await fetch("/api/admin/login",{method:"DELETE"});if(!r.ok)throw Error("Sign-out failed");setAuthenticated(false);setRecords(null);setSupport([]);}catch(e){setError(e instanceof Error?e.message:"Sign-out failed");}}}>Sign out</button><button className="underline ml-4" onClick={()=>void load().catch(e=>setError(e.message))}>Reload</button><h2 className="font-bold">All accounts - administrator only</h2>{records?<><section className="border rounded-xl p-4 text-sm space-y-2"><h3 className="font-bold">Live ledger - stored status, not real cover</h3><p>Policies: {records.live.policyRecords} · Claims: {records.live.claimRecords}</p><p>Premium marked paid: ₹{records.live.paidPremiumRecorded}</p><p>Claims marked paid: ₹{records.live.paidClaimsRecorded}</p><p>Recorded loss ratio: {records.live.lossRatio===null?"Insufficient data":records.live.lossRatio.toFixed(3)}</p></section><section className="border rounded-xl bg-amber-50 p-4 text-sm space-y-2"><h3 className="font-bold">Sandbox only - no money</h3><p>Policies: {records.sandbox.policyRecords} · Claims: {records.sandbox.claimRecords}</p><p>Simulated receipts: {records.sandbox.receiptRecords} · ₹{records.sandbox.receiptsSimulated}</p></section><p className="text-xs">As of {records.asOf}. No independent bank verification.</p></>:<p>Loading records...</p>}<h2 className="font-bold">Support request records</h2>{!support.length&&records&&<p>No support requests.</p>}{support.map(r=><article className="border rounded-xl p-4 space-y-2 text-sm" key={r.id}><h3 className="font-bold">{r.subject}</h3><p>{r.worker_name} · Priority {r.priority}</p><p>{r.description}</p><p>Stored status: {r.status}</p>{r.admin_notes&&<p>Notes: {r.admin_notes}</p>}<label>Status<select className="border p-2 ml-2" aria-label={`Status for ${r.subject}`} disabled={busy} value={r.status} onChange={e=>void updateRequest(r.id,e.target.value)}>{["open","in_progress","resolved","closed"].map(s=><option key={s}>{s}</option>)}</select></label></article>)}</>}<Link className="underline block" href="/dashboard">Worker dashboard</Link></div>;
}
