import test from "node:test";
import assert from "node:assert/strict";
import { createHash, randomUUID } from "node:crypto";
import { mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { NextRequest } from "next/server";
process.env.NODE_ENV = "test";
process.env.DATABASE_URL = "";
process.env.SQLITE_DB_PATH = join(mkdtempSync(join(tmpdir(), "shiftsafe-email-")), "ledger.db");
process.env.SEED_DEMO_DATA = "false";
process.env.FIREBASE_PROJECT_ID = "test-project";
process.env.WORKER_SESSION_SECRET = "email-worker-test-only-secret-1234567890";
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
test("email gate rejects plain Google grants, invalid actions, mismatches, expiry and replay", async () => {
  const { getDb } = await import("../backend/src/models/db");
  const { finishGoogleSignIn, consumeGoogleProof } = await import("../frontend/lib/server/google-onboarding");
  const { startEmailOnboarding, redeemEmailOnboarding } = await import("../frontend/lib/server/email-onboarding");
  const db = getDb();
  const identity = { subject: "google-fixture", email: "fixture@example.invalid", name: "Fixture" };
  const signed = await finishGoogleSignIn(identity);
  assert.equal(await consumeGoogleProof(signed.registrationProof!), null);
  let calls = 0;
  const sending = async () => { calls++; return { email: identity.email }; };
  await assert.rejects(startEmailOnboarding(identity, "fixture-token", "other@example.invalid", "9000000001", "http://localhost", sending), /Google account/);
  assert.equal(calls, 0);
  await startEmailOnboarding(identity, "fixture-token", identity.email, "9000000001", "http://localhost", sending);
  assert.equal(calls, 1);
  await assert.rejects(startEmailOnboarding(identity, "fixture-token", identity.email, "9000000001", "http://localhost", sending), /60 seconds/);
  assert.equal(calls, 1);
  const seed = async (expiry = Date.now() + 60000) => {
    const challenge = randomUUID();
    await db.prepare("INSERT INTO email_onboarding_challenges (id, subject, email, name, phone, expires_at) VALUES (?, ?, ?, ?, ?, ?)").run(hash(challenge), identity.subject, identity.email, identity.name, "9000000001", expiry);
    return challenge;
  };
  const challenge = await seed();
  await assert.rejects(redeemEmailOnboarding(challenge, "wrong-purpose", async () => ({ requestType: "PASSWORD_RESET", email: identity.email })), /does not verify/);
  await assert.rejects(redeemEmailOnboarding(challenge, "wrong-email", async () => ({ requestType: "VERIFY_EMAIL", email: "other@example.invalid" })), /does not verify/);
  await assert.rejects(redeemEmailOnboarding(await seed(0), "expired", sending), /expired/);
  const wrongSubject = await seed();
  await assert.rejects(redeemEmailOnboarding(wrongSubject, "valid-other-subject", async action => action === "resetPassword" ? { requestType: "VERIFY_EMAIL", email: identity.email } : { localId: "other", email: identity.email, emailVerified: true }), /different Google/);
  const provider = async (action: string) => action === "resetPassword" ? { requestType: "VERIFY_EMAIL", email: identity.email } : { localId: identity.subject, email: identity.email, emailVerified: true };
  const result = await redeemEmailOnboarding(challenge, "valid-email-code", provider);
  assert.equal(result.phone, "9000000001");
  assert.equal((await consumeGoogleProof(result.registrationProof))?.subject, identity.subject);
  assert.equal(await consumeGoogleProof(result.registrationProof), null);
  await assert.rejects(redeemEmailOnboarding(challenge, "valid-email-code", provider), /used/);
  const race = await seed();
  const results = await Promise.allSettled([redeemEmailOnboarding(race, "race-code", provider), redeemEmailOnboarding(race, "race-code", provider)]);
  assert.equal(results.filter(x => x.status === "fulfilled").length, 1);
  const fail = { ...identity, subject: "failed-send" };
  await assert.rejects(startEmailOnboarding(fail, "fixture-token", fail.email, "9000000001", "http://localhost", async () => { throw new Error("provider failure"); }), /provider failure/);
  assert.equal((await db.prepare("SELECT state FROM email_onboarding_challenges WHERE subject = ?").get(fail.subject)).state, "failed");
});
test("email API rejects cross-origin and missing Google identity", async () => {
  const send = await import("../frontend/app/api/auth/email/send/route");
  const redeem = await import("../frontend/app/api/auth/email/redeem/route");
  for (const route of [send, redeem]) assert.equal((await route.POST(new NextRequest("http://localhost/api/auth/email", { method: "POST", headers: { origin: "https://foreign.invalid" }, body: "{}" }))).status, 403);
  assert.equal((await send.POST(new NextRequest("http://localhost/api/auth/email", { method: "POST", headers: { origin: "http://localhost" }, body: "{}" }))).status, 401);
});
