import test from "node:test";
import assert from "node:assert/strict";
import { createHash, randomBytes } from "node:crypto";
import { mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { NextRequest } from "next/server";
process.env.NODE_ENV = "test";
process.env.DATABASE_URL = "";
process.env.SQLITE_DB_PATH = join(mkdtempSync(join(tmpdir(), "shiftsafe-email-")), "ledger.db");
process.env.SEED_DEMO_DATA = "false";
process.env.FIREBASE_PROJECT_ID = "test-project";
process.env.WORKER_SESSION_SECRET = "email-worker-test-only-secret-1234567890";
const hash = (value: string) => createHash("sha256").update(value).digest("hex");
test("email-only nonce rejects plain Google grants, leakage, old challenges, expiry and replay", async () => {
  const { getDb } = await import("../backend/src/models/db");
  const { finishGoogleSignIn, consumeGoogleProof } = await import("../frontend/lib/server/google-onboarding");
  const { startEmailOnboarding, redeemEmailOnboarding } = await import("../frontend/lib/server/email-onboarding");
  const db = getDb();
  const identity = { subject: "google-fixture", email: "fixture@example.invalid", name: "Fixture" };
  const signed = await finishGoogleSignIn(identity);
  assert.equal(await consumeGoogleProof(signed.registrationProof!), null);
  let calls = 0;
  let emailedNonce = "";
  const sending = async (action: string, body: Record<string, unknown>) => {
    calls++;
    assert.equal(action, "sendOobCode");
    assert.equal(body.requestType, "VERIFY_EMAIL");
    assert.equal(body.canHandleCodeInApp, false);
    const url = new URL(String(body.continueUrl));
    assert.equal(url.pathname, "/auth/email");
    assert.equal(url.search, "");
    emailedNonce = new URLSearchParams(url.hash.slice(1)).get("nonce")!;
    assert.match(emailedNonce, /^[0-9a-f]{64}$/);
    return { email: identity.email };
  };
  await assert.rejects(startEmailOnboarding(identity, "fixture-token", "other@example.invalid", "9000000001", "http://localhost", sending), /Google account/);
  assert.equal(calls, 0);
  const sendResult = await startEmailOnboarding(identity, "fixture-token", identity.email, "9000000001", "http://localhost", sending);
  assert.equal(JSON.stringify(sendResult).includes(emailedNonce), false);
  assert.equal((await db.prepare("SELECT id FROM email_onboarding_challenges WHERE subject = ?").get(identity.subject)).id, hash(emailedNonce));
  const emailResult = await redeemEmailOnboarding(emailedNonce);
  assert.equal(emailResult.email, identity.email);
  assert.equal(calls, 1);
  await assert.rejects(startEmailOnboarding(identity, "fixture-token", identity.email, "9000000001", "http://localhost", sending), /60 seconds/);
  assert.equal(calls, 1);
  const seed = async (expiry = Date.now() + 60000, state = "email-link-pending") => {
    const nonce = randomBytes(32).toString("hex");
    await db.prepare("INSERT INTO email_onboarding_challenges (id, subject, email, name, phone, expires_at, state) VALUES (?, ?, ?, ?, ?, ?, ?)").run(hash(nonce), identity.subject, identity.email, identity.name, "9000000001", expiry, state);
    return nonce;
  };
  await assert.rejects(redeemEmailOnboarding(""), /Invalid/);
  await assert.rejects(redeemEmailOnboarding("00000000-0000-0000-0000-000000000000"), /Invalid/);
  await assert.rejects(redeemEmailOnboarding(randomBytes(32).toString("hex")), /expired/);
  await assert.rejects(redeemEmailOnboarding(await seed(0)), /expired/);
  for (const state of ["pending", "sending", "failed", "used"]) await assert.rejects(redeemEmailOnboarding(await seed(Date.now() + 60000, state)), /expired/);
  const nonce = await seed();
  const result = await redeemEmailOnboarding(nonce);
  assert.equal(result.phone, "9000000001");
  assert.equal((await consumeGoogleProof(result.registrationProof))?.subject, identity.subject);
  assert.equal(await consumeGoogleProof(result.registrationProof), null);
  await assert.rejects(redeemEmailOnboarding(nonce), /used/);
  const race = await seed();
  const results = await Promise.allSettled([redeemEmailOnboarding(race), redeemEmailOnboarding(race)]);
  assert.equal(results.filter(x => x.status === "fulfilled").length, 1);
  const fail = { ...identity, subject: "failed-send" };
  await assert.rejects(startEmailOnboarding(fail, "fixture-token", fail.email, "9000000001", "http://localhost", async () => { throw new Error("provider failure"); }), /provider failure/);
  assert.equal((await db.prepare("SELECT state FROM email_onboarding_challenges WHERE subject = ?").get(fail.subject)).state, "failed");
});
test("email API rejects cross-origin and missing Google identity", async () => {
  const send = await import("../frontend/app/api/auth/email/send/route");
  const redeem = await import("../frontend/app/api/auth/email/redeem/route");
  for (const route of [send, redeem]) assert.equal((await route.POST(new NextRequest("http://localhost/api/auth/email", { method: "POST", headers: { origin: "https://foreign.invalid" }, body: "{}" }))).status, 403);
  assert.equal((await redeem.POST(new NextRequest("http://localhost/api/auth/email", { method: "POST", headers: { origin: "http://localhost" }, body: JSON.stringify({ challenge: "old", oobCode: "fake" }) }))).status, 400);
  assert.equal((await send.POST(new NextRequest("http://localhost/api/auth/email", { method: "POST", headers: { origin: "http://localhost" }, body: "{}" }))).status, 401);
});
