import test from "node:test";
import assert from "node:assert/strict";
import { generateKeyPair, SignJWT } from "jose";
import { mkdtempSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { NextRequest } from "next/server";
process.env.NODE_ENV = "test";
process.env.DATABASE_URL = "";
process.env.SQLITE_DB_PATH = join(mkdtempSync(join(tmpdir(), "shiftsafe-google-")), "ledger.db");
process.env.SEED_DEMO_DATA = "false";
process.env.FIREBASE_PROJECT_ID = "test-project";
process.env.WORKER_SESSION_SECRET = "google-worker-test-only-secret-1234567890";
function request(body: unknown, cookie?: string) { return new NextRequest("http://localhost/api/register", { method: "POST", headers: { origin: "http://localhost", "content-type": "application/json", ...(cookie ? { cookie } : {}) }, body: JSON.stringify(body) }); }
async function verifiedProof(identity: { subject: string; email: string; name: string }) {
  const { randomUUID, createHash } = await import("node:crypto");
  const { getDb } = await import("../backend/src/models/db");
  const { redeemEmailOnboarding } = await import("../frontend/lib/server/email-onboarding");
  const challenge = randomUUID();
  await getDb().prepare("INSERT INTO email_onboarding_challenges (id, subject, email, name, phone, expires_at) VALUES (?, ?, ?, ?, ?, ?)").run(createHash("sha256").update(challenge).digest("hex"), identity.subject, identity.email, identity.name, "9000000001", Date.now() + 60000);
  const result = await redeemEmailOnboarding(challenge, "fixture-provider-code", async action => action === "resetPassword" ? { requestType: "VERIFY_EMAIL", email: identity.email } : { localId: identity.subject, email: identity.email, emailVerified: true });
  return { ...result, registered: false };
}
test("Google token verification rejects invalid identity and signature", async () => {
  const { verifyGoogleIdentity } = await import("../frontend/lib/server/google-auth");
  const { privateKey, publicKey } = await generateKeyPair("RS256");
  const base = { email: "owner@example.invalid", email_verified: true, auth_time: Math.floor(Date.now() / 1000), firebase: { sign_in_provider: "google.com" } };
  const sign = (fields: Record<string, unknown> = {}, aud = "test-project", exp = "5m") => new SignJWT({ ...base, ...fields }).setProtectedHeader({ alg: "RS256" }).setIssuer("https://securetoken.google.com/test-project").setAudience(aud).setSubject("subject-a").setIssuedAt().setExpirationTime(exp).sign(privateKey);
  const key = async () => publicKey;
  assert.equal((await verifyGoogleIdentity(await sign(), key)).subject, "subject-a");
  for (const fields of [{ email_verified: false }, { firebase: { sign_in_provider: "password" } }, { auth_time: 1 }]) await assert.rejects(verifyGoogleIdentity(await sign(fields), key));
  await assert.rejects(verifyGoogleIdentity(await sign({}, "wrong-project"), key));
  await assert.rejects(verifyGoogleIdentity(await sign({}, "test-project", "-1s"), key));
  const wrong = await generateKeyPair("RS256");
  await assert.rejects(verifyGoogleIdentity(await sign(), async () => wrong.publicKey));
  delete process.env.FIREBASE_PROJECT_ID;
  await assert.rejects(verifyGoogleIdentity(await sign(), key), /not configured/);
  process.env.FIREBASE_PROJECT_ID = "test-project";
});
test("Google onboarding is subject-owned, not unverified-phone or email-owned", async (t) => {
  const { getDb } = await import("../backend/src/models/db");
  const { finishGoogleSignIn, consumeGoogleProof } = await import("../frontend/lib/server/google-onboarding");
  const register = await import("../frontend/app/api/register/route");
  const auth = await import("../frontend/lib/server/worker-auth");
  const { authorizeWorker } = await import("../frontend/lib/server/authorization");
  const session = await import("../frontend/app/api/auth/session/route");
  const db = getDb();
  const identity = { subject: "google-owner-a", email: "same@example.invalid", name: "Owner A" };
  const base = { name: "Owner A", phone: "9000000001", platform: "Zomato", city: "Mumbai", zone: "Andheri East", avgWeeklyIncome: 4200, daysWorkedThisWeek: 6, totalActiveDeliveryDays: 14, daysActiveInLast30: 14, consents: {}, authMethod: "google" };
  const proof = await verifiedProof(identity);
  assert.equal(proof.registered, false);
  const result = await register.POST(request({ ...base, email: "spoof@example.invalid", registrationProof: proof.registrationProof }));
  assert.equal(result.status, 200);
  const { workerId } = await result.json();
  const row = await db.prepare("SELECT phone, email FROM workers WHERE id = ?").get(workerId);
  assert.equal(row.phone, null); assert.equal(row.email, identity.email);
  const contact = await db.prepare("SELECT phone, phone_verified FROM worker_contacts WHERE worker_id = ?").get(workerId);
  assert.equal(contact.phone, base.phone); assert.equal(contact.phone_verified, 0);
  assert.equal((await register.POST(request({ ...base, registrationProof: proof.registrationProof }))).status, 401);
  const signed = await finishGoogleSignIn(identity);
  assert.equal(signed.registered, true);
  const cookie = `${auth.WORKER_SESSION_COOKIE}=${signed.token}`;
  const get = new NextRequest("http://localhost/api/auth/session", { headers: { cookie } });
  const projection = await (await session.GET(get)).json();
  assert.equal(projection.worker.phoneVerified, false); assert.equal(projection.worker.authProvider, "google"); assert.equal(projection.policy, null);
  assert.equal((await authorizeWorker(get, workerId)).workerId, workerId);
  const second = await verifiedProof({ ...identity, subject: "google-owner-b" });
  assert.equal(second.registered, false);
  const secondRes = await register.POST(request({ ...base, registrationProof: second.registrationProof }));
  assert.equal(secondRes.status, 200);
  assert.notEqual((await secondRes.json()).workerId, workerId);
  await t.test("concurrent proof consumption has one winner", async () => {
    const p = await verifiedProof({ ...identity, subject: "race" });
    assert.equal((await Promise.all([consumeGoogleProof(p.registrationProof!), consumeGoogleProof(p.registrationProof!)])).filter(Boolean).length, 1);
  });
  await t.test("expiry and changed subject revoke authorization", async () => {
    const p = await verifiedProof({ ...identity, subject: "expire" });
    await db.prepare("UPDATE google_registration_proofs SET expires_at = 0").run();
    assert.equal(await consumeGoogleProof(p.registrationProof!), null);
    await db.prepare("UPDATE worker_identities SET subject = ? WHERE worker_id = ?").run("changed", workerId);
    assert.equal((await authorizeWorker(get, workerId)).response?.status, 401);
    assert.equal((await (await session.GET(get)).json()).authenticated, false);
  });
  assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM premium_payments").get()).n, 0);
  assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM settlements").get()).n, 0);
});
test("Google endpoint origin and configuration fail closed", async () => {
  const { POST } = await import("../frontend/app/api/auth/google/route");
  const cross = new NextRequest("http://localhost/api/auth/google", { method: "POST", headers: { origin: "https://untrusted.invalid", "content-type": "application/json" }, body: "{}" });
  assert.equal((await POST(cross)).status, 403);
  delete process.env.FIREBASE_PROJECT_ID;
  const own = new NextRequest("http://localhost/api/auth/google", { method: "POST", headers: { origin: "http://localhost", "content-type": "application/json" }, body: "{}" });
  assert.equal((await POST(own)).status, 503);
  process.env.FIREBASE_PROJECT_ID = "test-project";
  assert.equal((await POST(own)).status, 401);
});
test("different Google proofs cannot create duplicate subject accounts", async () => {
  const { getDb } = await import("../backend/src/models/db");
  const register = await import("../frontend/app/api/register/route");
  const identity = { subject: "two-proof-race", email: "race@example.invalid", name: "Race" };
  const proofs = await Promise.all([verifiedProof(identity), verifiedProof(identity)]);
  const base = { name: "Race", phone: "9000000088", platform: "Zomato", city: "Mumbai", zone: "Andheri East", avgWeeklyIncome: 4200, daysWorkedThisWeek: 6, totalActiveDeliveryDays: 14, daysActiveInLast30: 14, consents: {}, authMethod: "google" };
  const results = await Promise.all(proofs.map(p => register.POST(request({ ...base, registrationProof: p.registrationProof }))));
  assert.equal(results.filter(r => r.status === 200).length, 1);
  assert.equal((await getDb().prepare("SELECT COUNT(*) AS n FROM worker_identities WHERE subject = ?").get(identity.subject)).n, 1);
  assert.equal((await getDb().prepare("SELECT COUNT(*) AS n FROM workers WHERE email = ?").get(identity.email)).n, 1);
});
