import test from "node:test";
import assert from "node:assert/strict";
import {mkdtempSync} from "node:fs";
import {tmpdir} from "node:os";
import {join} from "node:path";
import {NextRequest} from "next/server";
process.env.NODE_ENV="test";process.env.DATABASE_URL="";process.env.SQLITE_DB_PATH=join(mkdtempSync(join(tmpdir(),"sandbox-")),"ledger.db");process.env.SEED_DEMO_DATA="false";process.env.WORKER_SESSION_SECRET="sandbox-test-isolated-secret-not-deployed";
test("isolated sandbox lifecycle and evidence trust boundaries",async(t)=>{
 const {getDb}=await import("../backend/src/models/db"),db=getDb();const {quoteFingerprint,QUOTE_ASSUMPTIONS}=await import("../backend/src/engines/historical-quote");const s=await import("../backend/src/services/sandbox");const api=await import("../frontend/app/api/sandbox/route");const {WORKER_SESSION_COOKIE,createWorkerSessionToken}=await import("../frontend/lib/server/worker-auth");
 const now=Date.parse("2026-10-06T03:30:00Z");const inputs={city:"Mumbai",zone:"Andheri",platform:"Zomato",income:7000,weekdays:[0,1,2,3,4,5,6],startHour:0,endHour:24};const quote={status:"estimated",assumptions:QUOTE_ASSUMPTIONS,inputs,weeklyPremium:12,coverageAmount:30,calculation:{hourlyIncome:100}};
 for(const id of ["a","b"])await db.prepare("INSERT INTO workers (id,name,phone,city,zone,platform,avg_weekly_income) VALUES (?,?,?,?,?,?,?)").run(id,"Fixture Worker",id==="a"?"9000000001":"9000000002","Mumbai","Andheri","Zomato",7000);
 const cookie=`${WORKER_SESSION_COOKIE}=${createWorkerSessionToken("a","9000000001")}`;const req=(body?:unknown,c=cookie,origin="http://localhost")=>new NextRequest("http://localhost/api/sandbox",{method:body?"POST":"GET",headers:{cookie:c,origin,"content-type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});
 let policy:any,rain:any,heat:any;
 await t.test("authentication/origin/scope and invalid quote fail closed",async()=>{assert.equal((await api.GET(req(undefined,""))).status,401);assert.equal((await api.POST(req({action:"activate",confirmNoMoney:true},cookie,"http://other.invalid"))).status,403);assert.equal((await api.POST(req({action:"activate",workerId:"b",confirmNoMoney:true}))).status,403);assert.equal((await api.POST(req({action:"activate"}))).status,400);await assert.rejects(s.activateSandbox("a",now),/valid historical/);});
 await t.test("PostgreSQL timestamp offsets activate but old/future/invalid quotes remain blocked",async()=>{
  await db.prepare("INSERT INTO quote_snapshots (worker_id,input_fingerprint,result_json,created_at) VALUES (?,?,?,?)").run("b",quoteFingerprint(inputs),JSON.stringify(quote),"2026-10-06 03:00:00.123456+00");
  for(const stamp of ["2026-09-01 03:00:00.123456+00","2026-10-07 03:00:00.123456+00","invalid"]){await db.prepare("UPDATE quote_snapshots SET created_at=? WHERE worker_id=?").run(stamp,"b");await assert.rejects(s.activateSandbox("b",now),/old or has an invalid timestamp/);}
  await db.prepare("UPDATE quote_snapshots SET created_at=? WHERE worker_id=?").run("2026-10-06 03:00:00.123456+00","b");
  assert.equal((await s.activateSandbox("b",now)).premium_simulated,12);
  await db.prepare("DELETE FROM sandbox_policies WHERE worker_id=?").run("b");
 });
 await t.test("server priced activation concurrent replay creates one policy",async()=>{await db.prepare("INSERT INTO quote_snapshots (worker_id,input_fingerprint,result_json,created_at) VALUES (?,?,?,?)").run("a",quoteFingerprint(inputs),JSON.stringify(quote),"2026-10-06 03:00:00");const ps=await Promise.all([s.activateSandbox("a",now),s.activateSandbox("a",now)]);assert.equal(ps[0].id,ps[1].id);policy=ps[0];assert.equal(policy.premium_simulated,12);assert.equal(policy.weekly_limit,30);assert.equal(policy.ends_at-policy.starts_at,7*86400000);assert.equal((await db.prepare("SELECT COUNT(*) n FROM sandbox_policies").get()).n,1);});
 await t.test("synthetic scenarios explicitly labelled, duplicated once and missing evidence review",async()=>{await assert.rejects(s.scenarioEvent("b",policy.id,"heavy_rain","synthetic_complete",now),/not found/);const result=await Promise.all([s.scenarioEvent("a",policy.id,"heavy_rain","synthetic_complete",now),s.scenarioEvent("a",policy.id,"heavy_rain","synthetic_complete",now)]);rain=result[0];assert.equal(result[0].id,result[1].id);assert.equal(rain.status,"scenario_approved");const event=await db.prepare("SELECT evidence_json FROM sandbox_events WHERE id=?").get(rain.event_id);assert.match(event.evidence_json,/NOT OBSERVED WEATHER/);assert.equal(JSON.parse(event.evidence_json).realLossVerified,false);const missing=await s.scenarioEvent("a",policy.id,"heatwave","missing_evidence",now);assert.equal(missing.status,"review");assert.equal(missing.amount_simulated,0);await assert.rejects(s.settleSandbox("a",missing.id),/cannot be bypassed/);await assert.rejects(s.scenarioEvent("a",policy.id,"curfew","synthetic_complete",now),/Choose/);});
 await t.test("fresh provider threshold auto claim remains rule review; stale no fake claim",async()=>{const later=now+7200000;const provider=(async(url:unknown)=>new Response(JSON.stringify(String(url).includes("air-quality")?{}:{current:{time:later/1000,temperature_2m:42},current_units:{temperature_2m:"°C",wind_speed_10m:"km/h"},hourly:{time:[later/1000],rain:[30]},hourly_units:{rain:"mm"}}))) as typeof fetch;const weather=await s.checkSandboxWeather("a",policy.id,later,provider);assert.equal(weather.claims.length,2);assert.ok(weather.claims.every(c=>c.status==="review"&&c.amount_simulated===0));const again=await s.checkSandboxWeather("a",policy.id,later,provider);assert.deepEqual(again.claims.map(c=>c.id),weather.claims.map(c=>c.id));const early=await s.checkSandboxWeather("a",policy.id,now,provider);assert.equal(early.claims.length,0);const unavailable=await s.checkSandboxWeather("a",policy.id,later,(async()=>{throw Error("offline")}) as typeof fetch);assert.equal(unavailable.status,"unavailable");assert.equal(unavailable.claims.length,0);await assert.rejects(s.settleSandbox("a",weather.claims[0].id),/cannot be bypassed/);});
 await t.test("concurrent receipt retries honor weekly cap without live money",async()=>{heat=await s.scenarioEvent("a",policy.id,"heatwave","synthetic_complete",now);const receipts=await Promise.all([s.settleSandbox("a",rain.id),s.settleSandbox("a",rain.id),s.settleSandbox("a",heat.id)]);assert.equal(receipts[0].id,receipts[1].id);assert.ok(receipts.every(r=>r.label==="SIMULATED - NO MONEY TRANSFERRED"));assert.equal((await db.prepare("SELECT SUM(amount_simulated) total FROM sandbox_receipts").get()).total,30);assert.equal((await db.prepare("SELECT COUNT(*) n FROM sandbox_receipts").get()).n,2);assert.equal((await s.sandboxSnapshot("b")).claims.length,0);await assert.rejects(s.settleSandbox("b",rain.id),/not found/);for(const table of ["policies","claims","settlements","premium_payments","trigger_events"])assert.equal((await db.prepare(`SELECT COUNT(*) n FROM ${table}`).get()).n,0,table);});
 await t.test("settlement transaction failure leaves no partial receipt; retry same claim",async()=>{
  await db.prepare("DELETE FROM sandbox_receipts WHERE claim_id=?").run(heat.id);await db.prepare("UPDATE sandbox_claims SET status='scenario_approved' WHERE id=?").run(heat.id);
  await db.exec("CREATE TRIGGER fail_receipt BEFORE INSERT ON sandbox_receipts BEGIN SELECT RAISE(ABORT, 'fixture failure'); END");
  await assert.rejects(s.settleSandbox("a",heat.id),/fixture failure/);assert.equal(await db.prepare("SELECT id FROM sandbox_receipts WHERE claim_id=?").get(heat.id),undefined);assert.equal((await db.prepare("SELECT status FROM sandbox_claims WHERE id=?").get(heat.id)).status,"scenario_approved");
  await db.exec("DROP TRIGGER fail_receipt");assert.ok((await s.settleSandbox("a",heat.id)).id);
 });
 await t.test("changed quote cannot create overlapping sandbox policy",async()=>{
  await db.prepare("UPDATE quote_snapshots SET result_json=? WHERE worker_id=?").run(JSON.stringify({...quote,weeklyPremium:15}),"a");await assert.rejects(s.activateSandbox("a",now),/already exists/);assert.equal((await db.prepare("SELECT COUNT(*) n FROM sandbox_policies").get()).n,1);await db.prepare("UPDATE quote_snapshots SET result_json=? WHERE worker_id=?").run(JSON.stringify(quote),"a");
 });
 await t.test("profile change, expiry and changed quote deny event/activation",async()=>{await assert.rejects(s.scenarioEvent("a",policy.id,"heatwave","synthetic_complete",policy.ends_at),/outside/);await db.prepare("UPDATE workers SET zone=? WHERE id=?").run("Changed","a");await assert.rejects(s.activateSandbox("a",now),/no longer matches/);await assert.rejects(s.scenarioEvent("a",policy.id,"heatwave","synthetic_complete",now),/Profile changed/);await db.prepare("UPDATE workers SET zone=? WHERE id=?").run("Andheri","a");await db.prepare("UPDATE quote_snapshots SET created_at=? WHERE worker_id=?").run("2026-09-01 03:00:00","a");await assert.rejects(s.activateSandbox("a",now),/old/);});
});
