"use client";
import {useCallback,useEffect,useState} from "react";
import Link from "next/link";
import {useRouter} from "next/navigation";
import {useAppState} from "@/frontend/components/providers/AppProvider";
import {safeReplace} from "@/lib/client/navigation";
type Policy={id:string;premium_simulated:number;weekly_limit:number;starts_at:number;ends_at:number;status:string};
type Claim={id:string;policy_id:string;source:string;peril:string;status:string;observed_at:number;review_json:string;amount_simulated:number};
type Receipt={id:string;claim_id:string;amount_simulated:number;label:string};
type Snapshot={asOf:number;policies:Policy[];claims:Claim[];receipts:Receipt[]};
export default function SandboxPage(){
 const router=useRouter(),{isLoggedIn,isBootstrapping}=useAppState();const[data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 const load=useCallback(async()=>{try{const r=await fetch("/api/sandbox",{cache:"no-store"}),b=await r.json();if(!r.ok)throw Error(b.error||"Could not load sandbox");setData(b);setError("");}catch(e){setError(e instanceof Error?e.message:"Could not load sandbox");}},[]);
 useEffect(()=>{if(isBootstrapping)return;if(!isLoggedIn){safeReplace(router,"/login");return;}
 // Hydrate external sandbox account state.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 void load();},[isBootstrapping,isLoggedIn,router,load]);
 async function act(body:Record<string,unknown>){setBusy(true);setError("");setMessage("");try{const r=await fetch("/api/sandbox",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),b=await r.json();if(!r.ok)throw Error(b.error||"Sandbox action failed");if(b.message)setMessage(b.message);await load();}catch(e){setError(e instanceof Error?e.message:"Sandbox action failed");}finally{setBusy(false);}}
 return <main className="max-w-lg mx-auto p-4 pb-28 space-y-5"><div className="flex justify-between items-center gap-3"><h1 className="text-2xl font-bold">No-money sandbox</h1><Link className="underline text-sm" href="/journey">Quote journey</Link></div><div className="rounded-xl p-4 bg-amber-50 border border-amber-200 text-sm">SIMULATED ONLY. No money, bank transfer, UPI reference or real insurance. Sandbox policies, events, claims and receipts are separate from live financial records.</div><p className="text-sm">Quote → simulated premium → sandbox policy → event → rule review → simulated receipt. No trained fraud model exists. Missing evidence means review, never a clean fraud score.</p>
 <section className="border rounded-xl p-4 space-y-3"><h2 className="text-lg font-bold">1. Confirm simulated premium</h2><p className="text-sm">Uses your current saved historical quote, not editable client amounts. Seven days start on confirmation. Repeating the same quote confirmation restores the same policy, not a second purchase.</p><label className="flex gap-2 items-start text-sm"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>I understand this is a no-money simulation, not buying cover.</label><button disabled={!confirm||busy||!data} onClick={()=>act({action:"activate",confirmNoMoney:true})} className="bg-primary-500 text-white rounded px-4 py-2 disabled:opacity-50">Confirm simulated premium</button></section>
 {!data&&!error&&<p>Loading your sandbox records...</p>}
 {data?.policies.map(p=><section className="border rounded-xl p-4 space-y-4" key={p.id}><h2 className="text-lg font-bold">2. Sandbox policy</h2><dl className="grid grid-cols-2 text-sm gap-2"><dt>Premium simulated</dt><dd>₹{p.premium_simulated}</dd><dt>Weekly simulated limit</dt><dd>₹{p.weekly_limit}</dd><dt>Window (your timezone)</dt><dd>{new Date(Number(p.starts_at)).toLocaleString()} to {new Date(Number(p.ends_at)).toLocaleString()}</dd></dl><p className="text-xs break-all text-gray-500">{p.id}. Sandbox only; time window and saved profile checked before events.</p>
 <p className="text-sm">{Number(data.asOf)>=Number(p.ends_at)?"This sandbox window has expired. New events are blocked.":"Sandbox window open as of last refresh. This does not activate real insurance."}</p>
 <h3 className="font-semibold">3. Event and automatic sandbox claim</h3><button disabled={busy} onClick={()=>act({action:"weather",policyId:p.id})} className="border rounded p-2 text-sm">Check current modelled rain/heat</button><p className="text-sm">Only fresh in-policy and in-schedule crossings create claims. City-center model + missing activity/precise zone evidence always requires review. This is a manual check, not a recurring watch. No alerts or automatic sweep is enabled.</p>
 <div className="bg-slate-50 rounded p-3 space-y-2 text-sm"><h4 className="font-bold">Explicit synthetic scenarios</h4><p>These use a server-chosen scheduled hour within the sandbox window. They are not observations or verified losses. The complete-evidence fixture demonstrates receipt handling only.</p><div className="flex flex-wrap gap-2">{["heavy_rain","heatwave"].map(peril=><div key={peril} className="flex flex-col gap-2"><button disabled={busy} onClick={()=>act({action:"scenario",policyId:p.id,peril,evidenceCase:"missing_evidence",confirmSimulation:true})} className="border rounded p-2">Simulate {peril==="heavy_rain"?"rain":"heat"}: evidence missing</button><button disabled={busy} onClick={()=>act({action:"scenario",policyId:p.id,peril,evidenceCase:"synthetic_complete",confirmSimulation:true})} className="border rounded p-2">Simulate {peril==="heavy_rain"?"rain":"heat"}: complete fixture</button></div>)}</div></div>
 {data.claims.filter(c=>c.policy_id===p.id).map(c=><article className="border rounded p-3 space-y-2 text-sm" key={c.id}><h3 className="font-semibold">4. {c.peril} sandbox claim</h3><p className="break-all">Source: {c.source}. Status: {c.status}. Proposed simulated amount: ₹{c.amount_simulated}</p><p className="text-xs">{c.source.startsWith("manual_simulation")?"Synthetic scenario time (may be future-dated)":"Provider source time"}: {new Date(Number(c.observed_at)).toLocaleString()}</p><p>{c.source.startsWith("manual_simulation")?"Synthetic scenario, not real weather.":"Real fetched model estimate, not verified work-zone or income loss."}</p><ul className="list-disc pl-4">{(JSON.parse(c.review_json) as string[]).map(reason=><li key={reason}>{reason}</li>)}</ul>{c.status==="scenario_approved"&&<button disabled={busy} onClick={()=>act({action:"settle",claimId:c.id})} className="bg-slate-800 text-white rounded px-3 py-2">Create simulated receipt - no transfer</button>}{data.receipts.filter(r=>r.claim_id===c.id).map(r=><div key={r.id} className="bg-green-50 border border-green-200 p-3 rounded"><h4 className="font-bold">5. {r.label}</h4><p>₹{r.amount_simulated} simulated. Sandbox receipt, not payment evidence.</p><p className="text-xs break-all">{r.id}</p></div>)}</article>)}
 </section>)}
 {error&&<p role="alert" className="text-red-700">{error}</p>}{message&&<p role="status" className="text-sm">{message}</p>}<button className="underline text-sm" onClick={load}>Reload saved sandbox records</button><Link className="block underline" href="/dashboard">Dashboard</Link></main>;
}
